language: java
jdk:
 - oraclejdk8
script: ./gradlew check
 -DDB_URL=$DB_URL
 -DDB_USERNAME=$DB_USERNAME
 -DDB_PASSWORD=$DB_PASSWORD
 -DCLIENT_ID=$CLIENT_ID
 -DCLIENT_SECRET=$CLIENT_SECRET
 -DCLIENT_DOMAIN=$CLIENT_DOMAIN
 -DHIBERNATE_BEHAVIOR=$HIBERNATE_BEHAVIOR
 -DMANAGEMENT_API_AUDIENCE=$MANAGEMENT_API_AUDIENCE
before_install:
  - mysql -e 'CREATE DATABASE skiller'
deploy:
provider: heroku
api-key:
secure: $HEROKU_API_KEY
app: skiller
cache:
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
directories:
- $HOME/.gradle/caches/
- $HOME/.gradle/wrapper/
- $HOME/.gradle/nodejs/
- node_modules
services:
    - mysql